globalThis.CUSTOM_CATALOG_ITEMS = [
  {
    id: "custom-paradox-dg75",
    sheet: "Wlasny",
    index: "DG75",
    name: "Paradox DG75",
    category: "Czujnik ruchu PIR PET",
    producer: "PARADOX",
    shortDesc: "Cyfrowa czujka PIR z odpornością na zwierzęta do 40 kg",
    desc: "Wewnętrzna cyfrowa czujka ruchu PIR z podwójną optyką i odpornością na ruch zwierząt do 40 kg. Przeznaczona do stabilnej detekcji w pomieszczeniach, z zasięgiem około 11 x 11 m i kątem widzenia 90 stopni.",
    price: 280,
    image: "assets/paradox-dg75.jpg",
    searchAliases: "dg75 dg 75 paradox czujnik pir pet zwierzeta ruchu",
  },
  {
    id: "custom-satel-slim-pir-pet",
    sheet: "Wlasny",
    index: "SLIM-PIR-PET",
    name: "SATEL SLIM-PIR-PET",
    category: "Czujnik ruchu PIR PET",
    producer: "SATEL",
    shortDesc: "Czujka PIR z odpornością na zwierzęta do 20 kg",
    desc: "Czujka ruchu PIR z serii SLIM LINE, odporna na ruch zwierząt do 20 kg. Ma cyfrowy algorytm detekcji, kompensację temperatury, szerokokątną soczewkę oraz wbudowane rezystory parametryczne 2EOL.",
    price: 170,
    image: "assets/satel-slim-pir-pet.jpg",
    searchAliases: "satel slim pet slim pir pet czujnik pir zwierzeta ruchu",
  },
  {
    id: "custom-satel-slim-dual-pet",
    sheet: "Wlasny",
    index: "SLIM-DUAL-PET",
    name: "SATEL SLIM-DUAL-PET",
    category: "Czujnik ruchu PIR+MW PET",
    producer: "SATEL",
    shortDesc: "Czujka dualna PIR+MW z odpornością na zwierzęta do 20 kg",
    desc: "Dualna czujka ruchu PIR+MW z serii SLIM LINE, odporna na ruch zwierząt do 20 kg. Łączy czujnik podczerwieni i mikrofalowy, ma regulowaną czułość oraz cyfrową obróbkę sygnału ograniczającą fałszywe alarmy.",
    price: 280,
    image: "assets/satel-slim-dual-pet.jpg",
    searchAliases: "satel duo slim satel slim duo slim dual pet czujnik dualny pir mw zwierzeta ruchu",
  },
  {
    id: "custom-empty-row",
    sheet: "Wlasny",
    index: "PUSTE",
    name: "Pusty wiersz",
    category: "Pozycja wlasna",
    producer: "",
    shortDesc: "Własna pozycja do ręcznego opisu",
    desc: "",
    price: 0,
    image: "",
    customBlank: true,
    searchAliases: "puste pusty nowe nowy wiersz pozycja wlasna",
  },
];
